# Generated by Django 3.1.3 on 2021-01-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50, null=True)),
                ('main_image', models.URLField()),
                ('description', models.TextField(null=True)),
                ('show_time', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('director', models.CharField(max_length=50, null=True)),
                ('actor', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
